//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4330Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string Doc_Name { get; set; }
        public string KEYWORD { get; set; }
        public Nullable<int> TIMES_REPEATED { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
